<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\webform\WebformInterface;
use Drupal\webform\WebformSubmissionInterface;

use Uspdev\Senhaunica\Senhaunica;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Adiciona a checkbox na aba de configurações do Webform.
 */
function webform_senhaunica_webform_third_party_settings_form_alter(array &$form, FormStateInterface $form_state) {

    $webform = $form_state->getFormObject()->getEntity();

    $form['third_party_settings']['webform_senhaunica'] = [
        '#type' => 'details',
        '#title' => t('Universidade de São Paulo - Senha Única'),
        '#open' => FALSE,
    ];

    $form['third_party_settings']['webform_senhaunica']['habilitar_senhaunica'] = [
        '#type' => 'checkbox',
        '#title' => t('Habilitar senha única'),
        '#default_value' => $webform->getThirdPartySetting(
            'webform_senhaunica',
            'habilitar_senhaunica',
            FALSE
        ),
    ];
}
