<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\webform\WebformSubmissionInterface;


/**
 * Adiciona a checkbox na aba de configurações do Webform.
 */
function webform_senhaunica_webform_third_party_settings_form_alter(array &$form, FormStateInterface $form_state) {

  $webform = $form_state->getFormObject()->getEntity();

  $form['third_party_settings']['webform_senhaunica'] = [
    '#type' => 'details',
    '#title' => t('Universidade de São Paulo - Senha Única'),
    '#open' => FALSE,
  ];

  $form['third_party_settings']['webform_senhaunica']['habilitar_senhaunica'] = [
    '#type' => 'checkbox',
    '#title' => t('Habilitar senha única'),
    '#default_value' => $webform->getThirdPartySetting(
      'webform_senhaunica',
      'habilitar_senhaunica',
      FALSE
    ),
  ];

}


/**
 * Salva os dados da Senha Única quando o Webform é enviado.
 */
function webform_senhaunica_webform_submission_insert(WebformSubmissionInterface $submission) {

  $session = \Drupal::request()->getSession();


  // Recupera dados salvos no login da Senha Única.
  $numero_usp = $session->get('senhaunica_numero_usp');
  $nome = $session->get('senhaunica_nome_usuario');
  $email = $session->get('senhaunica_email');
  $hash = $session->get('senhaunica_hash');


  // Caso não exista autenticação Senha Única, não salva.
  if (!$numero_usp) {
    return;
  }


  // Salva na tabela customizada.
\Drupal::database()
  ->insert('webform_senhaunica')
  ->fields([
    'numero_usp' => $numero_usp,
    'nome_usuario' => $nome,
    'email' => $email,
    'hash' => $hash,
    'webform_id' => $submission->getWebform()->id(),
    'created' => date('Y-m-d H:i:s'),
  ])
  ->execute();


  \Drupal::logger('webform_senhaunica')->notice(
    'Usuário @usp salvo na tabela webform_senhaunica.',
    [
      '@usp' => $numero_usp,
    ]
  );

}